### ISSUE TITLE
Broken Wonders

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1123]
**Date & Time**: 
Sept 29, 2016
5:04 PM MST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 
"NPC"

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

Various wonders are broken and won't attack. 

Tiger in Yhoat doesn't TP or attack.
Shark in the dunes only TPs, and doesn't seem to build TP from BLU spells for some reason.
KSNM monkey doesn't attack or TP.

There might be others.

Go agro some and don't attack it, just sit there and watch it stare at you for hours of entertainment.

**Comment by TeoTwawki** [comment]
@R3P0FFXI I fixed this and somehow its unfixed. ARG

**Comment by TeoTwawki** [comment]
@tb1 should be fixed now..let me know.

**Comment by tb1** [comment]
Shark hitting hard, I haven't checked Tiger and don't have the KSNMs for the ape.

If I notice the issue again, I'll opening another ticket.

**Comment by TeoTwawki** [comment]
Thanks.

**Comment by tb1** [comment]
Tiger (Darrcuiln) still doesn't attack and just lets you beat on him.

**Comment by TeoTwawki** [comment]
dammit :(

**Comment by TeoTwawki** [comment]
Omigawd are his scripts ever screwed up..Temp setting him to normal melee, will fix prope rlater
