### ISSUE TITLE
Rdm Maat fight / he is resistant to elemental magic

### ISSUE THREAD

**Issue by neofreakjr** [LegionDark/Issues#1226]
**Date & Time**: 10 nov 2016, 15:20

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: crotos

**Nation**: bastok

**Job(level)/Sub Job(level)**: rdm70/blu35

**NPC or Monster or item Name**: maat fight

**Zone name**: waughroon shrine

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: maat was resisting elemental magic even though i was capped on enf and ele and ate a puff. He resisted extremely 80% of the damaging spells. This issue is after the 08 nov maintenance because two weeks ago i beat maat with two other chars on rdm. Same issue i saw on nasomi a year ago. Maat is working normal on other aspects, can be slept bind silenced and he hits for his normal damage, only problem is spells hit him for 20-70 damage and an occasional 100+.

**Comment by TeoTwawki** [comment]
Please tell darkstar on their tracker, its why its still like this is because they need to hear it.

**Comment by TeoTwawki** [comment]
The only custom thing legion has for any Maat fight, is him gaining an identical food buff to the player when custom food is used.

**Comment by neofreakjr** [comment]
I see, so need to post this on dark star too... ok

**Comment by TeoTwawki** [comment]
I rarely ask ppl to do it but I don't want it getting ignored for another year or 3 like most bugs that aren't legion specific..

**Comment by neofreakjr** [comment]
Ok posted it. I hope they will fix it

**Comment by TeoTwawki** [comment]
Thanks.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/3532

**Comment by Raelious** [comment]
@TeoTwawki Im 99.9% sure this has been fixed. I entered RDM Maat on a 70 RDM and rarely got any resists, spells were hitting for 140-290 looking at some screenshots of retail RDM maat fights seems to be on par with what spells were hitting him for there. Closing this as it seems to have been fixed at some point?

**Comment by TeoTwawki** [comment]
@Raelious Nothing happened in dsp for it at all. the primary issue on their end is that their resist calc is garbage - you can get all resists, no resists, or random mixes, all at teh same skill level. **_To much dice roll not enough actual math._** Which leads to unlucky players having 4+ runs at Maat and still failing.

Leaving this closed though. The next person to have rdm hell can open a new one and I'll link dsp again. Without fresh reminders nobody in DSP will look at it.
