### ISSUE TITLE
Kraken Club Failed to place on AH

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1279]
**Date & Time**: 
Dec 14,2016 // 4ish pm est

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sucidalderp

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
Drk99/Sam49

**NPC or Monster or item Name**: 
Kraken Club

**Zone name**: 
Labyrinth of Onzozo

**Coordinates (use `$where`)**: 
x-26 y11 z-59

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/17440/kraken-club

**Multi-boxing? (multiple clients on same connection)**: 
yes x6

**Steps To Reproduce / any other info**: 
I tried to place kraken club on AH twice for 20 million and it failed to place item on ah  both times.  So I traded it to my Alt Sucidaltank and now it cant be used traded or put up on ah now.  There is one up on Auction house right now but I do not know if that is what I tried to put up on ah or not

**Comment by sucidaldeathtar** [comment]
forgot to put the time  2ish pm est

**Comment by sucidaldeathtar** [comment]
no wait sorry 4ish pm est

**Comment by TeoTwawki** [comment]
try relogging? sounds like maybe dsp might have a flag-change related bug (they should not be changing, but flags determine what you are able to do with an item).

**Comment by sucidaldeathtar** [comment]
Sucidalderp dced for some reason and I logged out sucidaltank and relogged and it still show I don't have k club on AH on Sucidalderp and it is greyed out on Sucidaltank yet

**Comment by TeoTwawki** [comment]
the ah part inst relevant and almost confused me about what the issue is. What I currently believe the issue is, is that they item is "locked" on your character. A similar thing happens during synthesis, and there is even related bug which is normally solved by re-logging.

Best bet here to for us to destroy and recreate the item, I'll be on in a minute.

**Comment by sucidaldeathtar** [comment]
Ok its not greyed out but it still fails to place on ah.  So that's the only issue now

**Comment by sucidaldeathtar** [comment]
ok nevermind it just place on ah

**Comment by sucidaldeathtar** [comment]
SO it fixed itself logging all my toons out.  Sorry about that

**Comment by TeoTwawki** [comment]
ok, glad its taken care of now :)

**Comment by R3P0FFXI** [comment]
@sucidaldeathtar Stop calling this shit toons this isnt WOW! :)
