### ISSUE TITLE
Dynamis-Valkurm - Loss of Subjob on Entrance

### ISSUE THREAD

**Issue by Vaneticorum** [LegionDark/Issues#1595]
**Date & Time**: 7/30/17 - 2029 cst 

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Vaneticorum

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 99THF/DNC49

**NPC or Monster or item Name**: N/A

**Zone name**: Dynamis - Valkurm

**Coordinates (use `$where`)**: X: 124 Y: -7 Z: 110 (52)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**:  Enter with any of the options and lose subjob. I tried them all and three sent me in without sub. Also, all gear seems to get unequipped.

**Comment by TeoTwawki** [comment]
Known, fixed in DSp and we';; have a maint announced soon

**Comment by Jessland86** [comment]
https://github.com/LegionDark/Issues/issues/1599

**Comment by TeoTwawki** [comment]
left issue open after maint because have seen several ppl say its still a prob.

possibly dyna specific this time. was every battlefield effect before maint.

**Comment by Jessland86** [comment]
Confirmed, still an issue. Also the above limbus ate them too.

**Comment by TeoTwawki** [comment]
LameBuses is a good plural in my opinion >.>

👴 🚌

**Comment by Jessland86** [comment]
Issue was taken care of in today's maintenance.
