### ISSUE TITLE
Ragnarok Quest: Goblin took my Gold Ranpeere coin

### ISSUE THREAD

**Issue by ivanmn** [LegionDark/Issues#348]
Date & Time: September 27 2015
Frequency: Once
FFXI Client Version: 30150730_2
Character Name: Orichi
Race: Taru
Main Job: Warrior
Sub Job: Samurai
Area & Coordinates: Castle Zvahl Baileys, (I-8) Map 1
Party or Solo: Solo
NPC Name: Switchstix
Monster Name: Not applicable
Multi-boxing? (multiple clients on same connection): NO
Steps To Reproduce The Issue:

Tried to trade all items for Raganarok at the blank space in Beaucedine Glacier (g-10) as per ffxi-wiki. Nothing happened. 
Went to Switchstix to try. First had cutscence talking to the ???. Then talked to Switchstix, and he says to trade him the Ranperre Goldpiece which I did. He says "My buddies are going to hear about this 1 Ranperre Goldpiece. You should have been born a gob".
Says to leave Valhalla with him. Try to trade Valhalla + Necropsyche + Intricate Fragment with him, it goes straight to "are you sure you want to cancel the process" and starts calling me crazy.

Not sure what to do now, as Goldpiece missing, and no way for me to get ragnarok.

**Comment by TeoTwawki** [comment]
@ivanmn Investigating. This was allegedly fixed in darkstar over a month ago, and you are never ever supposed to trade him that Ranperre Goldpiece. What items specifically have been removed from your inventory, and which items do you still have?

@R3P0FFXI @Loki79 what I need here is a volunteer to use `@additem` to go through very step of this and verify what is happening, to make sure people aren't mistakenly cancelling and to verify the in game texts actually match what they should be. If this is busted it needs reported to darkstar.

**Comment by ivanmn** [comment]
Hello. only item i lost was the Ranperre Goldcoin that the goblin asked me to trade to him.
Here is a picture of where the conversation and actions done with the goblin. (market by yellow arrow) I still have the Valhalla, Necropsyche and Intricate Fragment with me.

![orichi_2015 09 27_144439](https://cloud.githubusercontent.com/assets/14860280/10123331/3faac732-652f-11e5-909f-72832a684823.png)

**Comment by TeoTwawki** [comment]
@ivanmn k, I'll be in game momentarily to see if we can make your game progress. I don't understand how the coin loss is possible: its specifically coded to reject that item and just display the message without taking it.

**Comment by TeoTwawki** [comment]
What should have happened, is you get a cs with your weapon talking, then at the designated '???' NPC you give that, rather than the goblin, your item(s).

**Comment by ivanmn** [comment]
Thanks for the quick reply. The goblin seemed more than happy to have taken my coin though.

**Comment by TeoTwawki** [comment]
Got this character taken care of, leaving issue open till tests and any needed adjustments are done.

**Comment by TeoTwawki** [comment]
Switchstix should now (again) be incapable of doing this BS again.
